"""
Django settings for UchroProject project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Home',
    'MainGameUI'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'UchroProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'UchroProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOGIN_URL = 'login_page'          # fallback si on va sur une page protégée
LOGIN_REDIRECT_URL = 'home'       # où rediriger après login réussi (fallback non-AJAX)
LOGOUT_REDIRECT_URL = 'home'
SESSION_COOKIE_SECURE = True      # HTTPS (conseillé en prod)
CSRF_COOKIE_SECURE = True         # idem
SESSION_COOKIE_SAMESITE = 'Lax'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


### CHARGEMENT DES MODULES ###
MODULES_DIR = BASE_DIR / "modules"

# Optionnel: limiter aux modules explicitement activés
MODULES_ENABLED = None
#os.getenv("MODULES_ENABLED", "").split(",") if os.getenv("MODULES_ENABLED") else None

def list_modules():
    if not MODULES_DIR.exists():
        return []
    slugs = [d.name for d in MODULES_DIR.iterdir() if d.is_dir()]
    return [s for s in slugs if (MODULES_DIR / s / "manifest.py").exists()
            and (MODULES_ENABLED is None or s in MODULES_ENABLED)]

DISCOVERED_MODULES = list_modules()

# Templates: on ajoute le répertoire templates de chaque module
TEMPLATES[0]["DIRS"] += [MODULES_DIR / slug / "templates" for slug in DISCOVERED_MODULES]

# Statics: on ajoute le répertoire static de chaque module
STATICFILES_DIRS += [MODULES_DIR / slug / "static" for slug in DISCOVERED_MODULES]

# Contexte global: manifest résolu en URLs statiques
TEMPLATES[0]["OPTIONS"]["context_processors"] += [
    "GameModules.context_processors.modules_manifest",
]

# Expose à l’app cœur
GAME_MODULES_SETTINGS = {
    "DIR": MODULES_DIR,
    "SLUGS": DISCOVERED_MODULES,
}